stages:
  - compile
  - build
  - deploy

compile-java:
  stage: compile
  image: maven:3-jdk-13
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/sprint-petclinic*.jar

deploy:
  stage: deploy
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  before_script:
    - echo ${GCP_SERVERLESS} >> serverless.json
  script:
    - gcloud auth activate-service-account --key-file=serverless.json
    - gcloud config set run/region europe-west1
    - gcloud config set project ${GCP_PROJECT_ID}
    - sed -i 's/${NV_API_KEY}/'${NV_API_KEY}'/g' cloudbuild.yml
    - gcloud builds submit . --config=cloudbuild.yml
  environment:
    name: nerdvision-demo-petclinic
